language: objective-c
osx_image: xcode9.4
xcode_project: Test.xcodeproj
xcode_scheme: Test
xcode_sdk: iphonesimulator11.2

branches:
    only:
        - master
env:
    - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
