language: objective-c
osx_image: xcode9.4.1
xcode_project: Test.xcodeproj
xcode_scheme: Test
xcode_sdk: iphonesimulator11.4

branches:
    only:
        - master
env:
    - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

script:
    - xcodebuild clean test -project Test.xcodeproj -scheme Test -destination 'platform=iOS Simulator,name=iPhone 6s,OS=11.4' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
